### ISSUE TITLE
(Re)start the Service

### ISSUE THREAD

**Issue by philharmonie** [achetibi/win-supervisor#1]
There is one important thing that made me crazy, that is missing in your (by the way) perfect instruction.
Once everything is setup, you must go to the windows services and start the service!

What I want to know, once the service is started, is there a way to restart the worker from the windows terminal, so that I could add the service restart to my deployment bat?

**Comment by achetibi** [comment]
Hello,

First of all thank you for your comment, if you want to modify the service to start it automatically at the system startup, you can do it manually by opening the **Microsoft Console Management**, for that you can type `services.msc` in the terminal, then find the service you want to modify **Supervisor** for example, right click on it and open properties, finally change the startup type to **Automatic** and click OK

If you want to install it and configure it to start automatically you can add the flag --type with auto as value

**Example**
`cygrunsrv --install Supervisor --type auto --path /bin/python --args "/usr/local/bin/supervisord -n -c /etc/supervisord.conf"`

Then to start the service you can run
`cygrunsrv --start Supervisor`

To answer your second question, yes you can start/restart the service from your terminal by using the command
```
cygrunsrv --stop Supervisor && cygrunsrv --start Supervisor
```

**Comment by philharmonie** [comment]
Thank you for you detailed answer. That helps me very much and adds more clearance to it.
```
cygrunsrv --stop Supervisor && cygrunsrv --start Supervisor
```
was, what I am looking for, but this is working in the Cygwin64 Terminal only. In the Windows Terminal it is not working and in consequence, I can't restart the worker from my `deploy.bat` file that I run over ssh headless.

**Comment by achetibi** [comment]
You can run the Windows command as admin to start/stop a service `net start Supervisor`
To restart the service you can run as admin `net stop Supervisor && net start Supervisor`

**Comment by philharmonie** [comment]
`net stop Supervisor; net start Supervisor` did the job. Thank you very much!
